name: mgmt_contacts
version: 0.0.4
author: Dzenan Ridjanovic
description: mgmt_entities application that uses dartling for its model.
homepage: http://ondart.me/
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling:
    git: https://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: https://github.com/dzenanr/dartling_default_app.git
